namespace ZeroGravity.Shared.Enums
{
    //    ALERT_NO_ALERT(0x0),
    //ALERT_BLE_ERROR(0x00001),
    //ALERT_FAULT_DETECTED_IN_THE_LOGGING_MEMORY(0x0002),
    //ALERT_BATTERY_LOW(0x00004),
    //ALERT_BATTERY_EXHAUSTED(0x00008),
    //ALERT_POWER_DOWN_SEQUENCE_ACTIVATED(0x0010),
    //ALERT_INVALID_BLE_PARAMETERS(0x00020),
    //ALERT_GLUCOSE_INTEGRITY_TEST_FAILED(0x00040),
    //ALERT_GLUCOSE_SKIPPED_MEASUREMENT(0x00080),
    //ALERT_GLUCOSE_RESULT_OUT_OF_RANGE(0x00100),
    //ALERT_TEMPERATURE_OUT_OF_RANGE(0x00200),
    //ALERT_SELF_TEST_FAILED_ADC(0x00800),
    //ALERT_SELF_TEST_FAILED_TEMP(0x01000),
    //ALERT_SELF_TEST_FAILED_BATT(0x02000),
    //ALERT_SELF_TEST_FAILED_CLK(0x04000),
    //ALERT_SELF_TEST_FAILED_MEM(0x08000),
    //ALERT_PATCH_CONNECTED(0x010000),
    //ALERT_BATTERY_STATUS(0x020000),
    //ALERT_INITIALISATION_FAILURE(0x040000),
    //ALERT_INVALID_PARAMETERS(0x080000),
    //ALERT_TRANSMITTER_STARTUP(0x100000),
    //ALERT_SELF_TEST_FAILED_WDOG(0x200000),
    //ALERT_SELF_TEST_FAILED_BLE(0x400000),
    //ALERT_SELF_TEST_FAILED_SRAM(0x800000),
    //ALERT_PATCH_NOT_CONNECTED(0x00400),


    // 1   ALERT_BLE_ERROR(0x00001, R.string.ALERT_BLE_ERROR, null, false),
    //2 ALERT_FAULT_DETECTED_IN_THE_LOGGING_MEMORY(0x0002, R.string.ALERT_FAULT_DETECTED_IN_THE_LOGGING_MEMORY, null, false),
    //4 ALERT_BATTERY_LOW(0x00004, R.string.ALERT_BATTERY_LOW, new AlertCharacteristics(new AlertCharacteristics.ExcludingAlertFilter(), new AlertCharacteristics.ExcludingAlertFilter(), null), false),
    // 8 ALERT_BATTERY_EXHAUSTED(0x00008, R.string.ALERT_BATTERY_EXHAUSTED, null, false),
    //16 ALERT_POWER_DOWN_SEQUENCE_ACTIVATED(0x0010, R.string.DEVICE_ERROR, null, true),
    // 32  ALERT_INVALID_BLE_PARAMETERS(0x00020, R.string.ALERT_INVALID_BLE_PARAMETERS, null, false),
    //64 ALERT_GLUCOSE_INTEGRITY_TEST_FAILED(0x00040, R.string.ALERT_GLUCOSE_INTEGRITY_TEST_FAILED, new AlertCharacteristics(AlertSeverityEnum.LOW, false, false, false, false, new AlertCharacteristics.TimeLimitExcludingAlertFilter(10), new AlertCharacteristics.ExcludingAlertFilter(), null), false),
    //128 ALERT_GLUCOSE_SKIPPED_MEASUREMENT(0x00080, R.string.ALERT_GLUCOSE_SKIPPED_MEASUREMENT, new AlertCharacteristics(new AlertCharacteristics.ExcludingAlertFilter(), new AlertCharacteristics.ExcludingAlertFilter(), null), false),
    //256 ALERT_GLUCOSE_RESULT_OUT_OF_RANGE(0x00100, R.string.ALERT_GLUCOSE_RESULT_OUT_OF_RANGE, null, false),
    //512 ALERT_TEMPERATURE_OUT_OF_RANGE(0x00200, R.string.ALERT_TEMPERATURE_OUT_OF_RANGE, null, false),
    //1024 ALERT_PATCH_NOT_CONNECTED(0x00400, R.string.ALERT_PATCH_NOT_CONNECTED, new AlertCharacteristics(AlertSeverityEnum.LOW, true, false, true, true, new AlertCharacteristics.CombinedExclusionAlertFilter(AlertBitmapEnum.ALERT_BATTERY_STATUS), null, new AlertCharacteristics.CombinedExclusionAlertFilter(AlertBitmapEnum.ALERT_BATTERY_STATUS)), false);
    //2048  ALERT_SELF_TEST_FAILED_ADC(0x00800, R.string.DEVICE_ERROR, null, true),
    //4096 ALERT_SELF_TEST_FAILED_TEMP(0x01000, R.string.DEVICE_ERROR, null, true),
    //8192 ALERT_SELF_TEST_FAILED_BATT(0x02000, R.string.DEVICE_ERROR, new AlertCharacteristics(new AlertCharacteristics.ExcludingAlertFilter(), new AlertCharacteristics.ExcludingAlertFilter(), null), true),
    //16384 ALERT_SELF_TEST_FAILED_CLK(0x04000, R.string.DEVICE_ERROR, null, true),
    //32768 ALERT_SELF_TEST_FAILED_MEM(0x08000, R.string.DEVICE_ERROR, null, true),
    //65536 ALERT_PATCH_CONNECTED(0x010000, R.string.ALERT_PATCH_CONNECTED, null, false),
    //131072 ALERT_BATTERY_STATUS(0x020000, R.string.DEVICE_ERROR, new AlertCharacteristics(new AlertCharacteristics.ExcludingAlertFilter(), new AlertCharacteristics.ExcludingAlertFilter(), null), true),
    //262144 ALERT_INITIALISATION_FAILURE(0x040000, R.string.DEVICE_ERROR, null, true),
    //524288 ALERT_INVALID_PARAMETERS(0x080000, R.string.DEVICE_ERROR, null, true), /*not used*/
    //1048576 ALERT_TRANSMITTER_STARTUP(0x100000, R.string.ALERT_TRANSMITTER_STARTUP, null, false),
    //2097152 ALERT_SELF_TEST_FAILED_WDOG(0x200000, R.string.DEVICE_ERROR, null, true),
    //4194304 ALARM_SELF_TEST_FAILED_BLE(0x400000, R.string.DEVICE_ERROR, null, true),
    //8388608 ALARM_SELF_TEST_FAILED_SRAM(0x800000, R.string.DEVICE_ERROR, null, true),





    public enum AlertCode
    {
        ALERT_NO_ALERT = 0,
        ALERT_BLE_ERROR = 1,
        ALERT_FAULT_DETECTED_IN_THE_LOGGING_MEMORY = 2,
        ALERT_BATTERY_LOW = 4,
        ALERT_BATTERY_EXHAUSTED = 8,
        ALERT_POWER_DOWN_SEQUENCE_ACTIVATED = 16,
        ALERT_INVALID_BLE_PARAMETERS = 32,
        ALERT_GLUCOSE_INTEGRITY_TEST_FAILED = 64,
        ALERT_GLUCOSE_SKIPPED_MEASUREMENT = 128,
        ALERT_GLUCOSE_RESULT_OUT_OF_RANGE = 256,
        ALERT_TEMPERATURE_OUT_OF_RANGE = 512,
        ALERT_PATCH_NOT_CONNECTED=1024,
        ALERT_SELF_TEST_FAILED_ADC = 2048,
        ALERT_SELF_TEST_FAILED_TEMP = 4096,
        ALERT_SELF_TEST_FAILED_BATT = 8192,
        ALERT_SELF_TEST_FAILED_CLK = 16384, 
        ALERT_SELF_TEST_FAILED_MEM = 32768,
        ALERT_PATCH_CONNECTED = 65536,
        ALERT_BATTERY_STATUS = 131072,
        ALERT_INITIALISATION_FAILURE = 262144,
        ALERT_INVALID_PARAMETERS = 524288,
        ALERT_TRANSMITTER_STARTUP = 1048576,
        ALERT_SELF_TEST_FAILED_WDOG = 2097152,
        ALERT_SELF_TEST_FAILED_BLE = 4194304,
        ALERT_SELF_TEST_FAILED_SRAM = 8388608
    }
}

//you will get a images here
//you have a 3-4 bugs
//