namespace ZeroGravity.Shared.Enums
{
    public enum CRCCodes
    {
        CRIT_ERROR_NO_ERROR = 0,
        CRIT_ERROR_CRC_FAILURE = 1,
        CRIT_ERROR_NO_PRIVILEGES = 2,
        CRIT_ERROR_WRONG_SIZE = 3,
        CRIT_ERROR_NULL_PARAMETER = 4,
        CRIT_ERROR_MISSING_POINTER = 5,
        CRIT_ERROR_ARRAY_OUT_OF_BOUNDS=6,
        CRIT_ERROR_LIMIT_UNDEFINED=7,
        CRIT_ERROR_WRONG_ARRAY_SIZE = 8,
        CRIT_ERROR_INVALID_TYPE = 9,
        CRIT_ERROR_QUEUE_EMPTY = 10,
        CRIT_ERROR_QUEUE_FULL = 11,
        CRIT_ERROR_NO_RESOURCE = 12,
        CRIT_ERROR_INVALID_INDEX = 13,
        CRIT_ERROR_INVALID_STATE = 14,
        CRIT_ERROR_INVALID_TRANSITION = 15,
        CRIT_ERROR_SM_STACK_FULL = 16,
        CRIT_ERROR_SM_STACK_EMPTY = 17,
        CRIT_ERROR_MISSING_TRANSITION_TABLE = 18,
        CRIT_ERROR_ASSERT_FAILURE = 19,
        CRIT_ERROR_HARDFAULT = 20,
        CRIT_ERROR_MEM_MANAGE = 21,
        CRIT_ERROR_BUSFAULT = 22,
        CRIT_ERROR_USAGEFAULT = 23,
        CRIT_ERROR_SVC_CALL = 24,
        CRIT_ERROR_DEBUGMON = 25,
        CRIT_ERROR_PEND_SVC = 26,
        CRIT_ERROR_INITIALISATION_FAULT = 27,
        CRIT_ERROR_BLE_HAL = 28,
        CRIT_ERROR_SELF_TEST = 29
    }
}

